#!/usr/bin/env bash

if [ "$#" -lt 1 ]; then
  echo "Usage: exifcaption photo1 [photo2 ...]"
  exit 1
fi

for f in "$@"; do
  if [ ! -f "$f" ]; then
    echo "File not found: $f" >&2
    continue
  fi

  echo
  echo "$f"

exiftool -api requestall -n -s3 -p '📸 ${Model} + ${LensModel}
${FocalLength;$_ =~ s/ mm$//; $_ = sprintf("%.0fmm", $_)} ${ShutterSpeed}s f/$Aperture ISO${ISO}${ExposureCompensation; $_ = (defined($_) && abs($_) >= 0.05) ? sprintf(" %+.1fEV", $_) : ""; s/\.0EV$/EV/;}' "$f"

done | tee /dev/stderr | pbcopy
